'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Alert, Avatar, Card, Empty, Skeleton, Tag } from 'antd';
import { ArrowLeftOutlined, EnvironmentOutlined, StarFilled, TeamOutlined } from '@ant-design/icons';
import AppShell from '@/components/AppShell';
import { api } from '@/lib/api';
type Review = { rating: number; comment?: string; created_at: string; shift_title?: string };
type Profile = { id: string; name: string; university?: string; major?: string; skills?: string[]; rating?: number | null; address?: string; phone?: string; verified?: boolean; history: { id: string; shift_id?: string; title: string; company_name?: string; location?: string; status: string; start_time: string }[]; reviews: Review[] };
const statusLabel: Record<string, string> = { PENDING: 'Đang chờ', INVITED: 'Được mời', ACCEPTED: 'Đã nhận', COMPLETED: 'Hoàn thành', REJECTED: 'Từ chối', DECLINED: 'Đã từ chối', OPEN: 'Đang tuyển', FULL: 'Đủ người', CLOSED: 'Đã đóng' };
export default function PublicProfile({ params }: { params: Promise<{ role: string; id: string }> }) {
  const [route, setRoute] = useState<{ role: string; id: string } | null>(null); const [data, setData] = useState<Profile | null>(null); const [error, setError] = useState('');
  useEffect(() => { params.then(setRoute).catch(() => setError('Không thể đọc hồ sơ')); }, [params]);
  useEffect(() => { if (!route || !['student', 'employer'].includes(route.role)) return; api<Profile>('/api/' + (route.role === 'student' ? 'students' : 'employers') + '/' + encodeURIComponent(route.id) + '/profile').then(setData).catch(cause => setError(cause.message)); }, [route]);
  const isStudent = route?.role === 'student';
  return <AppShell><div className="role-page profile-public-page"><Link href={isStudent ? '/candidates' : '/student/shifts'} className="pricing-back"><ArrowLeftOutlined /> Quay lại</Link>{error && <Alert type="error" title={error} />}{!route || (!data && !error) ? <Skeleton active /> : data && <><div className="role-heading"><div><span className="eyebrow">HỒ SƠ {isStudent ? 'ỨNG VIÊN' : 'DOANH NGHIỆP'}</span><h1>{data.name}</h1><p>{isStudent ? 'Thông tin, lịch sử nhận ca và đánh giá từ các doanh nghiệp.' : 'Thông tin doanh nghiệp, lịch sử ca và đánh giá từ sinh viên.'}</p></div></div><div className="profile-grid"><Card className="profile-avatar-card"><div className="profile-avatar-banner" aria-hidden="true">{isStudent ? <TeamOutlined /> : <EnvironmentOutlined />}</div><Avatar size={112} className="profile-avatar">{data.name.slice(0, 1).toUpperCase()}</Avatar><h2>{data.name}</h2><p className="profile-role">{isStudent ? [data.university, data.major].filter(Boolean).join(' · ') || 'Sinh viên EduShift' : data.verified ? 'Doanh nghiệp đã xác minh' : 'Doanh nghiệp EduShift'}</p>{data.rating != null && <div className="profile-rating"><StarFilled /> {Number(data.rating).toFixed(1)} / 5</div>}{data.address && <small>{data.address}</small>}</Card><div className="profile-public-main"><Card><h2>{isStudent ? 'Kỹ năng & thông tin' : 'Thông tin doanh nghiệp'}</h2>{isStudent ? <><div className="job-tags">{data.skills?.length ? data.skills.map(skill => <Tag key={skill}>{skill}</Tag>) : <span>Chưa cập nhật kỹ năng</span>}</div></> : <p>{data.phone || 'Chưa công khai số điện thoại'}</p>}</Card><Card><h2>Lịch sử {isStudent ? 'nhận ca' : 'đăng ca'}</h2>{data.history.length ? <div className="profile-history">{data.history.map(item => <div className="profile-history-row" key={item.id}><div><b>{item.title}</b><small>{item.company_name || item.location || ''} · {new Date(item.start_time).toLocaleString('vi-VN')}</small></div><Tag color={item.status === 'COMPLETED' ? 'green' : item.status === 'ACCEPTED' || item.status === 'OPEN' ? 'blue' : 'default'}>{statusLabel[item.status] || item.status}</Tag></div>)}</div> : <Empty description="Chưa có lịch sử" />}</Card><Card><h2>Đánh giá</h2>{data.reviews.length ? <div className="profile-reviews">{data.reviews.map((review, index) => <div className="profile-review" key={review.created_at + index}><b><StarFilled /> {review.rating}/5</b>{review.shift_title && <small> · {review.shift_title}</small>}<p>{review.comment || 'Không có nhận xét.'}</p><small>{new Date(review.created_at).toLocaleDateString('vi-VN')}</small></div>)}</div> : <Empty description="Chưa có đánh giá" />}</Card></div></div></>}</div></AppShell>;
}
