'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Alert, Empty, Input, Skeleton, Tag } from 'antd';
import { CalendarOutlined, EnvironmentOutlined, PlusOutlined, SearchOutlined, TeamOutlined } from '@ant-design/icons';
import AppShell from '@/components/AppShell';
import { api } from '@/lib/api';
type Shift = { id: string; title: string; location: string; start_time: string; end_time: string; status: string; applicants: number };
const labels: Record<string, string> = { OPEN: 'Đang tuyển', FULL: 'Đã đủ người', DRAFT: 'Bản nháp' };
export default function Shifts() { const [rows, setRows] = useState<Shift[] | null>(null); const [filter, setFilter] = useState('ALL'); const [search, setSearch] = useState(''); const [error, setError] = useState(''); useEffect(() => { api<Shift[]>('/api/shifts').then(setRows).catch(e => setError(e.message)); }, []); const filtered = useMemo(() => (rows || []).filter(row => (filter === 'ALL' || row.status === filter) && `${row.title} ${row.location}`.toLowerCase().includes(search.toLowerCase())), [rows, filter, search]); return <AppShell><div className="role-page employer-page"><div className="role-heading"><div><span className="eyebrow">DOANH NGHIỆP / TUYỂN DỤNG</span><h1>Ca làm việc</h1><p>Tạo và theo dõi các ca làm việc đang tuyển.</p></div><Link href="/shifts/new" className="action-button"><button className="primary"><PlusOutlined /> Đăng ca mới</button></Link></div>{error && <Alert type="error" title={error} />}{!rows ? (error ? null : <Skeleton active />) : <><div className="toolbar"><div className="tabs">{[['ALL','Tất cả'],['OPEN','Đang tuyển'],['FULL','Đã đủ người'],['DRAFT','Bản nháp']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div><Input prefix={<SearchOutlined />} placeholder="Tìm ca làm việc..." value={search} onChange={event => setSearch(event.target.value)} style={{ width: 240 }} /></div><section className="panel table-panel"><div className="table-head"><span>CA LÀM VIỆC</span><span>THỜI GIAN</span><span>ỨNG VIÊN</span><span>TRẠNG THÁI</span><span /></div>{filtered.length ? filtered.map(shift => <div className="table-row" key={shift.id}><div><b>{shift.title}</b><small><EnvironmentOutlined /> {shift.location}</small></div><div><b><CalendarOutlined /> {new Date(shift.start_time).toLocaleString('vi-VN', { dateStyle: 'short', timeStyle: 'short' })}</b><small>{new Date(shift.end_time).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}</small></div><b><TeamOutlined /> {shift.applicants}</b><Tag color={shift.status === 'OPEN' ? 'green' : 'default'}>{labels[shift.status] || shift.status}</Tag><Link href={'/candidates?shift_id=' + shift.id} className="candidate-link">Xem ứng viên</Link></div>) : <div className="empty-table"><Empty description="Không có ca phù hợp" /></div>}</section></>}</div></AppShell>; }
