'use client';
import { useEffect, useState } from 'react';
import { Alert, Button, Empty, Skeleton, Tag } from 'antd';
import { BellOutlined, CheckCircleOutlined, ClockCircleOutlined, TeamOutlined } from '@ant-design/icons';
import AppShell from '@/components/AppShell';
import { api } from '@/lib/api';
type Notification = { id: string; title: string; body: string; kind: string; is_read: boolean; created_at: string };
const kindMeta: Record<string, { color: string; icon: React.ReactNode }> = { APPLICATION: { color: 'magenta', icon: <TeamOutlined /> }, SUCCESS: { color: 'green', icon: <CheckCircleOutlined /> }, SHIFT: { color: 'gold', icon: <ClockCircleOutlined /> } };
export default function Notifications() { const [rows, setRows] = useState<Notification[] | null>(null); const [error, setError] = useState(''); useEffect(() => { api<Notification[]>('/api/notifications').then(setRows).catch(e => setError(e.message)); }, []); const markRead = async () => { await api('/api/notifications/read-all', { method: 'PATCH' }); setRows(items => items ? items.map(item => ({ ...item, is_read: true })) : items); }; return <AppShell><div className="role-page notifications-page"><div className="role-heading"><div><span className="eyebrow">TRUNG TÂM THÔNG BÁO</span><h1>Thông báo</h1><p>Cập nhật mới nhất về ca làm và hoạt động tài khoản.</p></div><Button onClick={markRead}>Đánh dấu đã đọc</Button></div>{error && <Alert type="error" title={error} />}{!rows ? <Skeleton active /> : <section className="panel notification-list">{rows.length ? rows.map(row => { const meta = kindMeta[row.kind] || { color: 'default', icon: <BellOutlined /> }; return <div className={'notification-row ' + (!row.is_read ? 'unread-row' : '')} key={row.id}><Tag color={meta.color} className="notification-icon">{meta.icon}</Tag><div><b>{row.title}</b><p>{row.body}</p><small>{new Date(row.created_at).toLocaleString('vi-VN')}</small></div>{!row.is_read && <span className="unread-dot" />}</div>; }) : <Empty description="Bạn đã cập nhật mọi thứ" />}</section>}</div></AppShell>; }
