import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors } from '../theme';
type SearchResult = { display_name: string; lat: string; lon: string };
type PhotonResult = { properties?: { name?: string; street?: string; city?: string; state?: string; country?: string }; geometry?: { coordinates?: [number, number] } };
type GeoPoint = { latitude: number; longitude: number };
type Props = { initialLocation?: string; onSelect: (place: { location: string; latitude: number; longitude: number }) => void };
const isVietnam = (latitude: number, longitude: number) => latitude >= 8 && latitude <= 24 && longitude >= 102 && longitude <= 110;
const nearest = (items: SearchResult[], point: GeoPoint | null) => point ? [...items].sort((a, b) => Math.hypot(Number(a.lat) - point.latitude, Number(a.lon) - point.longitude) - Math.hypot(Number(b.lat) - point.latitude, Number(b.lon) - point.longitude)) : items;
const unique = (items: SearchResult[]) => { const seen = new Set<string>(); return items.filter(item => { const key = Number(item.lat).toFixed(5) + ',' + Number(item.lon).toFixed(5); if (seen.has(key)) return false; seen.add(key); return true; }); };
async function photonSearch(value: string, signal: AbortSignal, point: GeoPoint | null): Promise<SearchResult[]> { const nearby = point ? '&lat=' + point.latitude + '&lon=' + point.longitude : ''; const response = await fetch('https://photon.komoot.io/api/?lang=default&limit=20' + nearby + '&q=' + encodeURIComponent(value), { signal }); if (!response.ok) throw new Error('search failed'); const data = await response.json() as { features?: PhotonResult[] }; return (data.features || []).flatMap(item => { const coordinates = item.geometry?.coordinates; if (!coordinates || !isVietnam(coordinates[1], coordinates[0])) return []; const p = item.properties || {}; const name = p.name || [p.street, p.city].filter(Boolean).join(', '); const display_name = [name, p.city, p.state, p.country].filter((part, index, all) => part && all.indexOf(part) === index).join(', '); return display_name ? [{ display_name, lat: String(coordinates[1]), lon: String(coordinates[0]) }] : []; }); }
export function OsmPlacePicker({ initialLocation = '', onSelect }: Props) {
  const [query, setQuery] = useState(initialLocation); const [results, setResults] = useState<SearchResult[]>([]); const [loading, setLoading] = useState(false); const [searched, setSearched] = useState(false); const [error, setError] = useState(false);
  const [nearby, setNearby] = useState<GeoPoint | null>(null); const [areaHint, setAreaHint] = useState('');
  useEffect(() => { navigator.geolocation?.getCurrentPosition(position => { const point = { latitude: position.coords.latitude, longitude: position.coords.longitude }; setNearby(point); fetch('https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=10&lat=' + point.latitude + '&lon=' + point.longitude, { headers: { 'Accept-Language': 'vi' } }).then(response => response.ok ? response.json() : Promise.reject(new Error('reverse failed'))).then(data => setAreaHint(data.address?.city || data.address?.town || data.address?.municipality || data.address?.state || '')).catch(() => undefined); }, () => undefined, { maximumAge: 300000, timeout: 5000 }); }, []);
  useEffect(() => { const value = query.trim(); if (value.length < 2) { setResults([]); setSearched(false); return; } const controller = new AbortController(); const timer = setTimeout(async () => { setLoading(true); setError(false); try { const scopedValue = areaHint && !value.toLocaleLowerCase().includes(areaHint.toLocaleLowerCase()) ? value + ' ' + areaHint : value; const viewbox = nearby ? '&viewbox=' + (nearby.longitude - 0.8) + ',' + (nearby.latitude + 0.8) + ',' + (nearby.longitude + 0.8) + ',' + (nearby.latitude - 0.8) : ''; const [nominatim, photon] = await Promise.allSettled([fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=12&countrycodes=vn&bounded=0' + viewbox + '&q=' + encodeURIComponent(scopedValue), { signal: controller.signal, headers: { 'Accept-Language': 'vi' } }).then(response => response.ok ? response.json() as Promise<SearchResult[]> : Promise.reject(new Error('search failed'))), photonSearch(scopedValue, controller.signal, nearby)]); const nominatimItems = nominatim.status === 'fulfilled' ? nominatim.value : []; const photonItems = photon.status === 'fulfilled' ? photon.value : []; const items = unique([...nominatimItems, ...photonItems].filter(item => isVietnam(Number(item.lat), Number(item.lon)))); if (!items.length && nominatim.status === 'rejected' && photon.status === 'rejected') throw new Error('search failed'); setResults(nearest(items, nearby).slice(0, 8)); setSearched(true); } catch (e) { if ((e as Error).name !== 'AbortError') { setError(true); setResults([]); setSearched(true); } } finally { if (!controller.signal.aborted) setLoading(false); } }, 450); return () => { clearTimeout(timer); controller.abort(); }; }, [query, nearby, areaHint]);
  return <View style={styles.wrap}><Text style={styles.label}>Tên quán / địa chỉ</Text><TextInput value={query} onChangeText={setQuery} placeholder='Ví dụ: bún ốc, Highlands Hồ Gươm...' placeholderTextColor={colors.muted} style={styles.input} autoCorrect={false} /><View style={styles.feedback}>{loading && <><ActivityIndicator size='small' color={colors.magenta} /><Text style={styles.hint}>Đang tìm địa điểm...</Text></>}{!loading && searched && !error && results.length === 0 && <Text style={styles.hint}>Chưa tìm thấy. Hãy thêm quận hoặc thành phố.</Text>}{error && <Text style={styles.error}>Không thể tìm địa điểm, hãy thử lại.</Text>}</View>{results.map(item => <Pressable key={item.lat + item.lon} onPress={() => { setQuery(item.display_name); setResults([]); onSelect({ location: item.display_name, latitude: Number(item.lat), longitude: Number(item.lon) }); }} style={styles.result}><Text style={styles.resultText}>{item.display_name}</Text></Pressable>)}</View>;
}
const styles = StyleSheet.create({ wrap: { gap: 7 }, label: { color: colors.ink, fontSize: 13, fontWeight: '700' }, input: { borderWidth: 1, borderColor: colors.line, borderRadius: 9, paddingHorizontal: 11, paddingVertical: 10, color: colors.ink, backgroundColor: '#fff' }, feedback: { minHeight: 18, flexDirection: 'row', alignItems: 'center', gap: 7 }, hint: { color: colors.muted, fontSize: 11 }, error: { color: '#9d3158', fontSize: 11 }, result: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.line, backgroundColor: '#fff' }, resultText: { color: colors.ink, fontSize: 12, lineHeight: 17 } });
