'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Alert, Button, Card, Empty, Skeleton, Tag, message } from 'antd';
import { ArrowLeftOutlined, CalendarOutlined, DollarOutlined, EnvironmentOutlined } from '@ant-design/icons';
import AppShell from '@/components/AppShell';
import LocationMap from '@/components/LocationMap';
import { api } from '@/lib/api';

type Shift = { id: string; employer_id?: string; company_name?: string; title: string; description?: string; location: string; latitude?: number | null; longitude?: number | null; start_time: string; end_time: string; hourly_rate: number; required_workers: number; required_skills: string[]; status: string; applied?: boolean; application_status?: string; available?: boolean; application_id?: string; };
const statusText: Record<string, string> = { PENDING: 'Đang chờ doanh nghiệp duyệt', ACCEPTED: 'Đã nhận ca', COMPLETED: 'Đã hoàn thành', INVITED: 'Được mời nhận ca', DECLINED: 'Đã từ chối lời mời', CANCELLED: 'Đã hủy ca', LEAVE_REQUESTED: 'Đang chờ duyệt xin nghỉ' };
export default function ShiftDetail({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(''); const [shift, setShift] = useState<Shift | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [messageApi, contextHolder] = message.useMessage();
  useEffect(() => { params.then(value => setId(value.id)).catch(() => setError('Không thể đọc ca làm')); }, [params]);
  useEffect(() => { if (id) api<Shift>('/api/shifts/' + encodeURIComponent(id)).then(setShift).catch(cause => setError(cause instanceof Error ? cause.message : 'Không tải được chi tiết ca')); }, [id]);
  const apply = async () => { if (!shift || busy) return; setBusy(true); try { await api('/api/applications', { method: 'POST', body: JSON.stringify({ shift_id: shift.id }) }); setShift({ ...shift, applied: true, application_status: 'PENDING' }); messageApi.success('Đã gửi đơn ứng tuyển'); } catch (cause) { messageApi.error(cause instanceof Error ? cause.message : 'Không thể ứng tuyển'); } finally { setBusy(false); } };
  return <AppShell>{contextHolder}<div className="role-page student-page shift-detail-page"><Link href="/student/shifts" className="pricing-back"><ArrowLeftOutlined /> Quay lại danh sách ca</Link>{error && <Alert type="error" title={error} />}{!shift && !error ? <Skeleton active /> : !shift ? <Empty description="Không tìm thấy ca làm" /> : <><div className="shift-detail-hero"><div><span className="eyebrow">CHI TIẾT CA LÀM</span><h1>{shift.title}</h1><p>{shift.company_name || 'Doanh nghiệp EduShift'}</p>{shift.employer_id && <Link className="profile-inline-link" href={'/profiles/employer/' + encodeURIComponent(shift.employer_id)}>Xem hồ sơ doanh nghiệp ↗</Link>}</div>{shift.application_status && <Tag color={shift.application_status === 'ACCEPTED' ? 'green' : 'orange'}>{statusText[shift.application_status] || shift.application_status}</Tag>}</div><div className="shift-detail-grid"><main><Card className="shift-overview-card"><div className="shift-stat-grid"><div><CalendarOutlined /><small>Thời gian</small><b>{new Date(shift.start_time).toLocaleDateString('vi-VN', { weekday: 'long', day: '2-digit', month: '2-digit', year: 'numeric' })}</b><span>{new Date(shift.start_time).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })} – {new Date(shift.end_time).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}</span></div><div><DollarOutlined /><small>Mức lương</small><b>{Number(shift.hourly_rate || 0).toLocaleString('vi-VN')} ₫</b><span>mỗi giờ</span></div><div><EnvironmentOutlined /><small>Địa điểm</small><b>{shift.location.split(',')[0]}</b><span>Nhấn xem bản đồ bên cạnh</span></div></div></Card><Card className="shift-description-card"><h2>Mô tả công việc</h2><p>{shift.description || 'Doanh nghiệp chưa thêm mô tả cho ca này.'}</p><h3>Yêu cầu kỹ năng</h3><div className="job-tags">{shift.required_skills.length ? shift.required_skills.map(skill => <Tag key={skill}>{skill}</Tag>) : <span className="muted-text">Không yêu cầu kỹ năng cụ thể</span>}</div></Card></main><aside><Card className="shift-location-card"><h2>Địa điểm làm việc</h2><LocationMap location={shift.location} latitude={shift.latitude} longitude={shift.longitude} /></Card><Card className="shift-action-card">{shift.applied || shift.application_status ? <><Tag color="green">{statusText[shift.application_status || 'PENDING'] || 'Đã gửi đơn'}</Tag><p>Thông tin trạng thái ca sẽ được cập nhật qua thông báo.</p></> : <><p>Kiểm tra kỹ thời gian và địa điểm trước khi ứng tuyển.</p><Button type="primary" size="large" block loading={busy} disabled={shift.available === false} onClick={() => void apply()}>{shift.available === false ? 'Không thể ứng tuyển' : 'Ứng tuyển ca này'}</Button></>}</Card></aside></div></>}</div></AppShell>;
}
