'use client';
import { useEffect, useState } from 'react';
type Props = { initialLocation?: string; initialLatitude?: number | null; initialLongitude?: number | null };
type SearchResult = { display_name: string; lat: string; lon: string };
function mapUrl(latitude: number, longitude: number) { const delta = 0.0035; return 'https://www.openstreetmap.org/export/embed.html?bbox=' + (longitude - delta) + ',' + (latitude - delta) + ',' + (longitude + delta) + ',' + (latitude + delta) + '&layer=mapnik&marker=' + latitude + ',' + longitude; }
export default function LocationPicker({ initialLocation = '', initialLatitude = null, initialLongitude = null }: Props) {
  const [query, setQuery] = useState(initialLocation); const [results, setResults] = useState<SearchResult[]>([]); const [selected, setSelected] = useState({ location: initialLocation, latitude: initialLatitude, longitude: initialLongitude });
  useEffect(() => { const value = query.trim(); if (value.length < 3 || value === selected.location) return; const timer = window.setTimeout(() => { fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=5&countrycodes=vn&q=' + encodeURIComponent(value), { headers: { 'Accept-Language': 'vi' } }).then(response => response.ok ? response.json() : Promise.reject(new Error('search failed'))).then((items: SearchResult[]) => setResults(items)).catch(() => setResults([])); }, 350); return () => window.clearTimeout(timer); }, [query, selected.location]);
  function choose(item: SearchResult) { setQuery(item.display_name); setResults([]); setSelected({ location: item.display_name, latitude: Number(item.lat), longitude: Number(item.lon) }); }
  const map = selected.latitude != null && selected.longitude != null ? mapUrl(selected.latitude, selected.longitude) : '';
  return <div className='location-picker'><label>Tên quán / địa chỉ<input name='location' required value={query} onChange={event => { setQuery(event.target.value); setResults([]); setSelected({ location: '', latitude: null, longitude: null }); }} placeholder='Tìm tên quán, số nhà, đường...' autoComplete='off' /></label>{results.length > 0 && <div className='location-results' role='listbox'>{results.map(item => <button type='button' key={item.lat + item.lon} onClick={() => choose(item)}>{item.display_name}</button>)}</div>}<input type='hidden' name='latitude' value={selected.latitude ?? ''} /><input type='hidden' name='longitude' value={selected.longitude ?? ''} /><p>Nhập tên quán hoặc địa chỉ rồi chọn kết quả OpenStreetMap để lưu vị trí chính xác.</p>{map && <iframe title='Vị trí đã chọn' loading='lazy' src={map} />}</div>;
}
